# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!
  USERNAME:
    sh: whoami
  HOSTNAME:
    sh: hostname

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  apply:
    desc: Apply Nix configuration
    cmds:
      - home-manager switch --flake .#{{.USERNAME}}@{{.HOSTNAME}} -b backup

  update:
    desc: Update packages
    cmds:
      - nix flake update
      - task: apply
      - task: changed

  changed:
    desc: Show what changed with last update
    cmds:
      - home-manager generations | head -n 2 | cut -d' ' -f 7 | tac | xargs   nix store diff-closures
