# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!
  USERNAME:
    sh: whoami
  HOSTNAME:
    sh: hostname

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  build:
    desc: Build Nix configuration
    cmds:
      - home-manager build --flake .#{{.USERNAME}}@{{.HOSTNAME}} -b backup

  apply:
    desc: Apply Nix configuration
    cmds:
      - home-manager switch --flake .#{{.USERNAME}}@{{.HOSTNAME}} -b backup

  update:
    desc: Update packages
    cmds:
      - nix flake update
      - task: apply
      - task: changed

  changed:
    desc: Show what changed with last update
    cmds:
      - home-manager generations | head -n 2 | cut -d' ' -f 7 | tail -r | xargs   nix store diff-closures

  cache-check:
    desc: Show which packages in the home config are missing from binary caches
    cmds:
      - home-manager build --flake .#{{.USERNAME}}@{{.HOSTNAME}}
      - nix run .#nix-cache-check -- -r -missing ./result
